import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import './globals.css';
import LocaleSwitcherDropdown from '@/components/layout/LocaleSwitcherDropdown';

const golos = Golos_Text({
	variable: '--font-golos',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: LayoutProps<'/[locale]'>) {
	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	// เปิด static rendering และกระจาย locale ไปยัง Server Components
	setRequestLocale(locale);

	// ส่ง messages เข้า Client Components ผ่าน Provider
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={`${golos.variable} antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<LocaleSwitcherDropdown />
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
